# Generated by Django 5.0.4 on 2024-08-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livre', '__first__'),
        ('util', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_jours', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remise_date', models.DateField(null=True)),
                ('return_at', models.DateField(null=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.abonne')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.bookinstance')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
            },
        ),
    ]
