# Generated by Django 5.0.4 on 2024-08-15 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0001_initial'),
        ('util', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='biblio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='util.bibliothecaire'),
        ),
    ]
