# Generated by Django 5.0.4 on 2024-08-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0002_emprunt_biblio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='return_at',
            field=models.DateTimeField(null=True),
        ),
    ]
